export class Img {

    links: any = [
        {name: 'Luke Skywalker', link: 'lucke.jpg'},
        {name: 'C-3PO', link: 'C3PO.png'},
        {name: 'R2-D2', link: 'R2D2.png'},
        {name: 'Darth Vader', link: 'Darth.jpg'},
        {name: 'Leia Organa', link: 'Leia.jpg'},
        {name: 'Owen Lars', link: 'Owen.jpg'},
        {name: 'Beru Whitesun lars', link: 'Beru.png'},
        {name: 'R5-D4', link: 'R5D4.jpg'},
        {name: 'Biggs Darklighter', link: 'Biggs.png'},
        {name: 'Obi-Wan Kenobi', link: 'obiwan.jpg'},
        {name: 'Anakin Skywalker', link: 'Anakin.jpg'},
        {name: 'Wilhuff Tarkin', link: 'Tarkin.jpg'},
        {name: 'Chewbacca', link: 'chewbacca.jpg'},
        {name: 'Han Solo', link: 'hansolo.jpg'},
        {name: 'Greedo', link: 'Greedo.jpg'},
        {name: 'Jabba Desilijic Tiure', link: 'Jabba.png'},
        {name: 'Wedge Antilles', link: 'wedge.png'},
        {name: 'Jek Tono Porkins', link: 'porkins.jpg'},
        {name: 'Yoda', link: 'yoda.jpg'},
        {name: 'Palpatine', link: 'Palpatine.jpg'},
        {name: 'Boba Fett', link: 'Boba.jpeg'},
        {name: 'IG-88', link: 'IG-88.jpeg'},
        {name: 'Bossk', link: 'Bossk.jpg'},
        {name: 'Lando Calrissian', link: 'Lando.jpeg'},
        {name: 'Lobot', link: 'Lobot.jpeg'},
        {name: 'Ackbar', link: 'Ackbar.jpeg'},
        {name: 'Mon Mothma', link: 'Mon.png'},
        {name: 'Arvel Crynyd', link: 'Arvel.jpg'},
        {name: 'Wicket Systri Warrick', link: 'Deej_Warrick.png'},
        {name: 'Nien Nunb', link: 'Nien.jpeg'},
        {name: 'Qui-Gon Jinn', link: 'qui-gon-jinn.jpg'},
        {name: 'Nute Gunray', link: 'Nute.jpeg'},
        {name: 'Finis Valorum', link: 'valorum_a31904f4.jpeg'},
        {name: 'Jar Jar Binks', link: 'jarjarbinks_1-750x380.jpg'},
        {name: 'Roos Tarpals', link: 'databank_generaltarpals_01_169_cb2134d2.jpeg'},
        {name: 'Rugor Nass', link: 'Nass-SW.jpg'},
        {name: 'Ric Olié', link: 'RicOlieRight.png'},
        {name: 'Watto', link: 'watto_930bd6c0.jpeg'},
        {name: 'Sebulba', link: 'sebulba_1f3fe180.jpeg'},
        {name: 'Quarsh Panaka', link: 'CW2yG6lWcAEdBwI.jpg'},
        {name: 'Shmi Skywalker', link: 'databank_shmiskywalkerlars_01_169_7449f0a8.jpeg'},
        {name: 'Darth Maul', link: 'DarthMaul.png'},
        {name: 'Bib Fortuna', link: 'maxresdefault.jpg'},
        {name: 'Ayla Secura', link: 'Aayla_Secura_002.jpg'},
        {name: 'Dud Bolt', link: 'Dud_Bolt_head.jpg'},
        {name: 'Gasgano', link: 'Gasgano.jpg'},
        {name: 'Ben Quadinaros', link: 'Ben.jpeg'},
        {name: 'Mace Windu', link: 'Mace-Windu.jpg'},
        {name: 'Ki-Adi-Mundi', link: 'Ki-Adi-Mundi.jpeg'},
        {name: 'Kit Fisto', link: 'Kit.jpeg'},
        {name: 'Eeth Koth', link: 'Eeth.JPG'},
        {name: 'Adi Gallia', link: 'databank_adigallia_169_8b798f27.jpeg'},
        {name: 'Saesee Tiin', link: 'Saesee_Tiin.png'},
        {name: 'Yarael Poof', link: 'Yarael.jpg'},
        {name: 'Plo Koon', link: 'databank_plokoon_01_169_92e6679c.jpeg'},
        {name: 'Mas Amedda', link: 'MasAmedda.jpg'},
        {name: 'Gregar Typho', link: 'Gregar.jpg'},
        {name: 'Cordé', link: 'Corde.jpg'},
        {name: 'Cliegg Lars', link: 'Cliegg.jpeg'},
        {name: 'Poggle the Lesser', link: 'Poggle_Geo.jpg'},
        {name: 'Luminara Unduli', link: 'Luminara.png'},
        {name: 'Barriss Offee', link: 'Barris3.jpg'},
        {name: 'Dormé', link: 'dorme36.jpg'},
        {name: 'Dooku', link: 'CountDooku.jpg'},
        {name: 'Bail Prestor Organa', link: 'Bail_office.jpg'},
        {name: 'Jango Fett', link: 'Jango.jpg'},
        {name: 'Zam Wesell', link: 'maxresdefault-1.jpg'},
        {name: 'Dexter Jettster', link: 'big_1477235919_image.jpg'},
        {name: 'Lama Su', link: 'databank_taunwe_01_169_9b9e8eb9.jpeg'},
        {name: 'Taun We', link: 'Taun.jpg'},
        {name: 'Jocasta Nu', link: 'jocasta-nu_a3b32f08.jpeg'},
        {name: 'Ratts Tyerell', link: '2368623-ratts_tyerell_2.jpg'},
        {name: 'R4-P17', link: '41KsoWRbdGL._SL500_AC_SS350_.jpg'},
        {name: 'Wat Tambor', link: 'Wat.jpg'},
        {name: 'San Hill', link: 'San_Hill_SW.jpg'},
        {name: 'Shaak Ti', link: 'shaak_ti_9523e7c7.jpeg'},
        {name: 'Grievous', link: 'Grievous.jpeg'},
        {name: 'Tarfful', link: 'Tarffulprofile.jpg'},
        {name: 'Raymus Antilles', link: 'Raymus.jpg'},
        {name: 'Sly Moore', link: 'sly-moore_6af90e66.jpeg'},
        {name: 'Tion Medon', link: 'Tion.jpeg'},
        {name: 'Finn', link: 'finn-main_952e10d2.jpeg'},
        {name: 'Rey', link: 'Rey.jpg'},
        {name: 'Poe Dameron', link: 'Poe.jpeg'},
        {name: 'BB8', link: 'BB8.jpg'},
        {name: 'Captain Phasma', link: 'captain-phasma-1-tall-1536x864.jpg'},
        {name: 'Padmé Amidala', link: 'Padme.jpg'}
    ]

}